---
- hosts: all
  tasks:
    - name: Download Tomcat using get_url
       get_url: url: http://10.10.10.98/rpi/skrypty/timesyncd.conf dest: /etc/systemd/timesyncd.conf
       become: root
       ecome_method: sudo
       ignore_errors: yes
       mode: 0755
