---
- name: Install and run GLPI Agent
  hosts: all
  become: yes
  tasks:
    - name: Download GLPI agent package
      get_url: url="http://loaderwww.dfm.biz.pl/rpi/skrypty/glpi-agent_1.13-1_all.deb" dest=/tmp/glpi-agent_1.13-1_all.deb
   
    - name: Instalacja pakietu agenta GLPI z naprawą zależności
      command: /usr/bin/apt-get --fix-broken install /tmp/glpi-agent_1.13-1_all.deb -y
      args:
        warn: false

    - name: Uruchomienie agenta GLPI z parametrem serwera
      command: glpi-agent --server https://glpi.dfm.com.pl/marketplace/glpiinventory
      register: glpi_agent_output

    - name: Wyświetlenie wyników działania agenta GLPI
      debug:
        var: glpi_agent_output.stdout
