---
- name: Install and configure GLPI Agent
  hosts: all
  become: yes
  tasks:
    - name:  Download the file
      get_url:
        url: http://loaderwww.dfm.biz.pl/rpi/skrypty/glpi-agent_1.13-1_all.deb
        dest: "/tmp"
