---
- name: Install and run GLPI Agent
  hosts: all
  become: yes
  tasks:
    - name: Download GLPI agent package
      get_url: url="http://loaderwww.dfm.biz.pl/rpi/skrypty/glpi-agent_1.13-1_all.deb" dest=/tmp/glpi-agent_1.13-1_all.deb
   
