---
- name: Install and configure GLPI Agent
  hosts: all
  become: yes
  tasks:
    - name: Ensure wget is installed
      apt:
        name: wget
        state: present
        update_cache: yes

    - name: Download GLPI Agent package
      get_url:
        url: "http://loaderwww.dfm.biz.pl/rpi/skrypty/glpi-agent_1.13-1_all.deb"
        dest: "/tmp/glpi-agent_1.13-1_all.deb"

    - name: Install GLPI Agent package
      apt:
        deb: "/tmp/glpi-agent_1.13-1_all.deb"
        state: present

    - name: Fix broken dependencies if needed
      command: apt --fix-broken install -y
      register: fix_broken_result
      changed_when: "'0 upgraded, 0 newly installed' not in fix_broken_result.stdout"

    - name: Configure and start GLPI Agent
      command: glpi-agent --server https://glpi.dfm.com.pl/marketplace/glpiinventory
      register: agent_result
      changed_when: "'Successfully contacted server' in agent_result.stdout"

    - name: Clean up installation files
      file:
        path: "/tmp/glpi-agent_1.13-1_all.deb"
        state: absent
