---

- hosts: all
  become: true
  tasks:
    - name: Install docker-compose
      get_url: 
        url: http://loaderwww.dfm.biz.pl/AnsibleFiels/autostart 
        dest: /etc/xdg/lxsession/LXDE-pi/autostart  
  
    - name: Reboot
      become: True
      reboot:
