---
- hosts: all
  tasks:
  -name: Update and upgrade apt packages
   become: true
   apt:
    update_cache: yes
    upgrade: 'yes'
  - name: Instal VirtualKeyboard
    apt:
     name: matchbox-keyboard
     state: present
     update_cache: true
    become: true
