---
- name: Ustaw boot_delay na Raspberry Pi i zrestartuj
  hosts: raspberry
  become: yes

  tasks:
    - name: Ustaw boot_delay=5 w /boot/firmware/config.txt
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: '^boot_delay='
        line: 'boot_delay=5'
        create: yes
        backup: yes

    - name: Restart Raspberry Pi
      reboot:
        msg: "Restart po ustawieniu boot_delay=5"
        reboot_timeout: 300
