---
- name: Ustaw parametry boot Raspberry Pi i zrestartuj
  hosts: raspberry
  become: yes

  tasks:
    - name: Ustaw boot_delay=5 w /boot/firmware/config.txt
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: '^boot_delay='
        line: 'boot_delay=5'
        create: yes
        backup: yes
      notify: reboot raspberry

    - name: Dopisz usbcore.autosuspend=-1 do /boot/firmware/cmdline.txt jeżeli brak
      replace:
        path: /boot/firmware/cmdline.txt
        regexp: '^(?!.*\busbcore\.autosuspend=-1\b)(.+)$'
        replace: '\1 usbcore.autosuspend=-1'
        backup: yes
      notify: reboot raspberry

  handlers:
    - name: reboot raspberry
      reboot:
        msg: "Restart po zmianie parametrów boot"
        reboot_timeout: 300
