---
- name: Uruchomienie GLPI Agent i zapisanie hostów z błędami
  hosts: all
  tasks:
    - name: Uruchomienie GLPI Agent z parametrem --server
      ansible.builtin.command: glpi-agent --server https://glpi.dfm.com.pl/marketplace/glpiinventory
      register: glpi_agent_output
      changed_when: false
      ignore_errors: yes

    - name: Zbieranie hostów, które zwróciły błąd
      set_fact:
        failed_hosts: "{{ failed_hosts | default([]) + [inventory_hostname] }}"
      when: glpi_agent_output.rc != 0

    - name: Zapisanie hostów do pliku CSV
      ansible.builtin.copy:
        content: |
          Host,Error Output
          {% for host in failed_hosts %}
          {{ host }},{{ glpi_agent_output.stderr }}
          {% endfor %}
        dest: "/var/glpi_failed_hosts.csv"
      when: failed_hosts is defined and failed_hosts | length > 0
