---
- name: Install and configure GLPI Agent
  hosts: all
  become: yes
  tasks:

    - name: Sprawdź, czy system to Jessie
      ansible.builtin.shell: cat /etc/os-release
      register: os_release

    - name: Zaktualizuj sources.list dla Jessie (raspbian)
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb http://raspbian.raspberrypi.org/raspbian/ jessie'
        line: 'deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free'
        state: present
      when: "'jessie' in os_release.stdout"

    - name: Zaktualizuj sources.list dla Jessie (archive)
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb http://mirrordirector.raspbian.org/raspbian/ jessie'
        line: 'deb http://archive.raspberrypi.org/debian/ buster main'
        state: present
      when: "'jessie' in os_release.stdout"

    - name: Usuń błędny plik konfiguracji APT (jeśli istnieje)
      ansible.builtin.file:
        path: /etc/apt/apt.conf.d/99releaseinfo
        state: absent

    - name: Usuń uszkodzone listy pakietów
      ansible.builtin.file:
        path: /var/lib/apt/lists
        state: absent

    - name: Utwórz pusty katalog list (APT)
      ansible.builtin.file:
        path: /var/lib/apt/lists
        state: directory
        mode: '0755'

    - name: Wyłącz ostrzeżenie o zmianie Suite (Release Info)
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/99disable-releaseinfo-change
        content: 'Acquire::AllowReleaseInfoChange "true";'
        mode: '0644'
      
    - name: Odśwież listę pakietów
      ansible.builtin.apt:
        update_cache: yes
      register: dpkg_result
      ignore_errors: yes   

    - name: Pobierz plik .deb GLPI Agent
      ansible.builtin.get_url:
        url: http://loaderwww.dfm.biz.pl/rpi/skrypty/glpi-agent_1.13-1_all.deb
        dest: /tmp/glpi-agent_1.13-1_all.deb

    - name: Zainstaluj GLPI Agent .deb przez dpkg
      ansible.builtin.command: dpkg -i /tmp/glpi-agent_1.13-1_all.deb
      register: dpkg_result
      ignore_errors: yes

    - name: Napraw brakujące zależności (apt-get -f install)
      ansible.builtin.command: apt-get install -f -y
      when: dpkg_result.rc != 0

    - name: Napraw nieskonfigurowane pakiety (dpkg --configure -a)
      ansible.builtin.command: dpkg --configure -a
      ignore_errors: yes

    - name: Wyczyść cache APT
      ansible.builtin.command: apt-get clean

    - name: Doinstaluj python-apt (jeśli potrzebny)
      ansible.builtin.apt:
        name: python-apt
        state: present
        install_recommends: no
      ignore_errors: yes

    - name: Uruchomienie GLPI Agent z parametrem --server
      ansible.builtin.command: glpi-agent --server https://glpi.dfm.com.pl/marketplace/glpiinventory
      register: glpi_agent_output
      changed_when: false
      ignore_errors: yes

    - name: Dodaj lub zaktualizuj wpis server w pliku agent.cfg
      ansible.builtin.lineinfile:
        path: /etc/glpi-agent/agent.cfg
        regexp: '^server='
        line: 'server=https://glpi.dfm.com.pl/marketplace/glpiinventory'
        create: yes
