---
- name: Install and configure GLPI Agent
  hosts: all
  become: yes

  tasks:
    - name: Sprawdź dostępność hostów (ping)
      ansible.builtin.ping:

    - name: Pobierz pakiet instalacyjny GLPI Agent
      ansible.builtin.get_url:
        url: http://loaderwww.dfm.biz.pl/rpi/skrypty/glpi-agent_1.13-1_all.deb
        dest: /tmp/glpi-agent_1.13-1_all.deb

    - name: Instaluj pakiet .deb przez apt (automatycznie rozwiązuje zależności)
      ansible.builtin.apt:
        deb: /tmp/glpi-agent_1.13-1_all.deb
        update_cache: yes

    - name: Upewnij się, że katalog konfiguracyjny istnieje
      ansible.builtin.file:
        path: /etc/glpi-agent
        state: directory
        mode: '0755'

    - name: Dodaj lub zaktualizuj wpis 'server' w pliku agent.cfg
      ansible.builtin.lineinfile:
        path: /etc/glpi-agent/agent.cfg
        regexp: '^server\s*='
        line: 'server = https://glpi.dfm.com.pl/marketplace/glpiinventory'
        create: yes

    - name: Uruchomienie GLPI Agent z parametrem --server
      ansible.builtin.command: glpi-agent --server https://glpi.dfm.com.pl/marketplace/glpiinventory
      register: glpi_agent_output
      changed_when: false

    - name: Wyświetlenie wyniku działania agenta
      ansible.builtin.debug:
        var: glpi_agent_output.stdout
