---
- name: Install and configure GLPI Agent
  hosts: all
  become: yes
  tasks:

    - name: Sprawdź, czy system jest oparty na Jessie
      ansible.builtin.shell: cat /etc/os-release
      register: os_release

    - name: Zaktualizuj repozytoria, jeśli system jest na Jessie
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb http://mirrordirector.raspbian.org/raspbian/ jessie'
        line: 'deb http://archive.raspberrypi.org/debian/ buster main contrib non-free rpi'
        state: present
      when: "'jessie' in os_release.stdout"

    - name: Dodaj repozytoria Raspbian do pliku sources.list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb http://raspbian.raspberrypi.org/raspbian/'
        line: 'deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free'
        state: present

    - name: Odśwież listę pakietów (apt update)
      ansible.builtin.apt:
        update_cache: yes

    - name: Pobierz plik .deb GLPI Agent
      get_url:
        url: http://loaderwww.dfm.biz.pl/rpi/skrypty/glpi-agent_1.13-1_all.deb
        dest: "/tmp/glpi-agent_1.13-1_all.deb"

    - name: Zainstaluj pakiet .deb GLPI Agent za pomocą dpkg
      ansible.builtin.command: dpkg -i /tmp/glpi-agent_1.13-1_all.deb
      register: dpkg_result
      ignore_errors: yes

    - name: Napraw brakujące zależności po dpkg
      ansible.builtin.command: apt-get install -y -f
      when: dpkg_result.rc != 0

    - name: Uruchomienie GLPI Agent z parametrem --server
      ansible.builtin.command: glpi-agent --server https://glpi.dfm.com.pl/marketplace/glpiinventory
      register: glpi_agent_output
      changed_when: false
      ignore_errors: yes

    - name: Dodaj lub zaktualizuj wpis server w pliku agent.cfg
      ansible.builtin.lineinfile:
        path: /
