---
- name: Install and configure GLPI Agent on Raspberry Pi
  hosts: all
  become: yes

  tasks:

    - name: Akceptuj zmiany w ReleaseInfo (APT Suite) – tymczasowo
      ansible.builtin.command: apt-get update --allow-releaseinfo-change
      register: apt_update
      changed_when: false

    - name: Dodaj trwałe zezwolenie na zmianę ReleaseInfo Suite
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/99releaseinfo
        content: 'APT::Get::AllowReleaseInfoChange "true";\n'
        owner: root
        group: root
        mode: '0644'

    - name: Odśwież cache pakietów
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Pobierz pakiet instalacyjny GLPI Agent
      ansible.builtin.get_url:
        url: http://loaderwww.dfm.biz.pl/rpi/skrypty/glpi-agent_1.13-1_all.deb
        dest: /tmp/glpi-agent_1.13-1_all.deb

    - name: Instaluj pakiet .deb przez apt (automatyczne zależności)
      ansible.builtin.apt:
        deb: /tmp/glpi-agent_1.13-1_all.deb

    - name: Upewnij się, że katalog konfiguracyjny istnieje
      ansible.builtin.file:
        path: /etc/glpi-agent
        state: directory
        mode: '0755'

    - name: Dodaj lub zaktualizuj wpis 'server' w pliku agent.cfg
      ansible.builtin.lineinfile:
        path: /etc/glpi-agent/agent.cfg
        regexp: '^server\s*='
        line: 'server = https://glpi.dfm.com.pl/marketplace/glpiinventory'
        create: yes

    - name: Uruchomienie GLPI Agent z parametrem --server
      ansible.builtin.command: glpi-agent --server https://glpi.dfm.com.pl/marketplace/glpiinventory
      register: glpi_agent_output
      changed_when: false
      ignore_errors: yes  # na wypadek, gdyby agent wymagał startu jako usługa

    - name: Wyświetlenie wyniku działania agenta
      ansible.builtin.debug:
        var: glpi_agent_output.stdout
