---
- name: Install and configure GLPI Agent
  hosts: all
  become: yes
  tasks:

    - name: Sprawdź, czy system jest oparty na Jessie
      ansible.builtin.shell: cat /etc/os-release
      register: os_release

    - name: Zaktualizuj repozytoria, jeśli system jest na Jessie
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb http://mirrordirector.raspbian.org/raspbian/ jessie'
        line: 'deb http://archive.raspberrypi.org/debian/ buster main'
        state: present
      when: "'jessie' in os_release.stdout"

    - name: Zaktualizuj repozytoria, jeśli system jest na Jessie (repozytorium Raspbian)
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb http://raspbian.raspberrypi.org/raspbian/ jessie'
        line: 'deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free'
        state: present
      when: "'jessie' in os_release.stdout"

    - name: Usuń plik 99releaseinfo jeśli istnieje
      ansible.builtin.file:
        path: /etc/apt/apt.conf.d/99releaseinfo
        state: absent

    

    - name: Wyczyść cache APT
      ansible.builtin.command: apt-get clean

    - name: Odśwież listę pakietów
      ansible.builtin.apt:
        update_cache: yes

    - name: Napraw zależności apt
      ansible.builtin.command: apt-get install -f -y

    - name: Pobierz plik .deb GLPI Agent
      get_url:
        url: http://loaderwww.dfm.biz.pl/rpi/skrypty/glpi-agent_1.13-1_all.deb
        dest: "/tmp/glpi-agent_1.13-1_all.deb"

    - name: Zainstaluj pakiet GLPI Agent
      ansible.builtin.apt:
        deb: /tmp/glpi-agent_1.13-1_all.deb

    - name: Dodaj lub zaktualizuj wpis server w pliku agent.cfg
      ansible.builtin.lineinfile:
        path: /etc/glpi-agent/agent.cfg
        regexp: '^server='
        line: 'server=https://glpi.dfm.com.pl/marketplace/glpiinventory'
        create: yes
