---
- name: Install and configure GLPI Agent
  hosts: all
  become: yes
  tasks:

    - name: Odśwież listę pakietów (apt update)
      ansible.builtin.apt:
        update_cache: yes

    - name: Download the file
      get_url:
        url: http://loaderwww.dfm.biz.pl/rpi/skrypty/glpi-agent_1.13-1_all.deb
        dest: "/tmp/glpi-agent_1.13-1_all.deb"

    - name: Install .deb package using dpkg
      ansible.builtin.command: dpkg -i /tmp/glpi-agent_1.13-1_all.deb
      register: dpkg_result
      ignore_errors: yes

    - name: Napraw brakujące zależności po dpkg
      ansible.builtin.command: apt-get install -y -f
      when: dpkg_result.rc != 0

    - name: Uruchomienie GLPI Agent z parametrem --server
      ansible.builtin.command: glpi-agent --server https://glpi.dfm.com.pl/marketplace/glpiinventory
      register: glpi_agent_output
      changed_when: false
      ignore_errors: yes

    - name: Dodaj lub zaktualizuj wpis server w pliku agent.cfg
      ansible.builtin.lineinfile:
        path: /etc/glpi-agent/agent.cfg
        regexp: '^server\s*='
        line: 'server = https://glpi.dfm.com.pl/marketplace/glpiinventory'
        create: yes

    - name: Wyświetlenie wyniku działania agenta
      ansible.builtin.debug:
        var: glpi_agent_output.stdout
