---
- name: Konfiguracja timesyncd na Raspberry Pi
  hosts: all
  become: yes

  tasks:
    - name: Pobranie pliku konfiguracyjnego timesyncd.conf
      get_url:
        url: http://10.10.10.98/rpi/skrypty/timesyncd.conf
        dest: /etc/systemd/timesyncd.conf
        mode: '0644'

    - name: Włączenie synchronizacji czasu (NTP)
      command: timedatectl set-ntp true

    - name: Przeładowanie konfiguracji systemd
      systemd:
        daemon_reload: yes

    - name: Restart usługi systemd-timesyncd
      systemd:
        name: systemd-timesyncd
        state: restarted
        enabled: yes
