---
- hosts: all
  become: true
  tasks:
  - name: Update Repository
    command: apt-get update -y --allow-releaseinfo-change
  - name: Update and upgrade apt packages
    become: true
    apt:
     update_cache: yes
     upgrade: 'yes'
  - name: Instal VirtualKeyboard
    apt:
     name: onboard
     state: present
     update_cache: true
    become: true
  - name: Reboot
    become: True
    reboot: 
